# Generated by Django 5.0.3 on 2024-03-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_user_country_user_fav_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('nepal', 'Nepal'), ('india', 'India'), ('china', 'China'), ('america', 'America'), ('australia', 'Australia'), ('canada', 'Canada')], default='nepal', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_sport',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
